### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by amalic** [Ontotext-AD/spring-data-semantic#11]
I would like to fork this and try to migrate it to rdf4j and a more current spring version.

LGPL would be cool.

**Comment by stefan-enev** [comment]
Hi amalic,

We will be more than happy for a fork, or to work with you on pull request with the proposed updates. The library is licensed under http://www.apache.org/licenses/LICENSE-2.0 at the moment, and we've completed most steps required to deploy the library to Maven Central (ref this guide - https://maven.apache.org/guides/mini/guide-central-repository-upload.html).

A good questions that comes to mind is, do we want to move this library as part of the Rdf4j project? To us it sounds like a good idea.

Thoughts?

Cheers,
Stefan

**Comment by amalic** [comment]
Sounds good. 
Contributing via pull requests is just fine. 
Apache license is just fine!

What do you mean by "move this library"?

Cheers,
Alex

**Comment by stefan-enev** [comment]
Contribute it here https://github.com/eclipse/rdf4j if the community sees it as a useful tool which could become a part of the project.

**Comment by amalic** [comment]
This could make sense. I guess first we need to switch over to rdf4j. I have so far updated springramework to latest version and OpenRDF. All Testcases seem to run. 

There's still some cleanup and refactoring to do:
- need to replace deprecated GraphUtil 
- need to discuss with you what to do with unused members and methods
- need to discuss with you why all testmethods in TestMappingPolicy are commented out

**Comment by amalic** [comment]
I've created a pull request. Please review. Not sure about replacing GraphUtil since it is not really covered by any Test case.
Used this [google groups posting](https://groups.google.com/d/msg/rdf4j-users/AwZjh8VTtxI/U8F9NLmjBAAJ) as a reference.

(I had troubles with eclipse and github --> this resulted ina couple of pull requests. i closed the ones where the Junit tests failed. Please check!!!)
